version: '2'

services:
  zoo1:
    image: wurstmeister/zookeeper
    restart: always
    hostname: zoo1
    container_name: zoo1
    ports:
      - "2181:2181" # client port
      - "2888:2888" # follower port
      - "3888:3888" # election port
    volumes:
      - "./zoo1/zoo.cfg:/opt/zookeeper-3.4.13/conf/zoo.cfg"
      - "./zoo1/data:/opt/zookeeper-3.4.13/data"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      zoo_kafka:
        ipv4_address: 172.23.0.11

  zoo2:
    image: wurstmeister/zookeeper
    restart: always
    hostname: zoo2
    container_name: zoo2
    ports:
      - "2182:2181"
      - "2889:2888"
      - "3889:3888"
    volumes:
      - "./zoo2/zoo.cfg:/opt/zookeeper-3.4.13/conf/zoo.cfg"
      - "./zoo2/data:/opt/zookeeper-3.4.13/data"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      zoo_kafka:
        ipv4_address: 172.23.0.12

  zoo3:
    image: wurstmeister/zookeeper
    restart: always
    hostname: zoo3
    container_name: zoo3
    ports:
      - "2183:2181"
      - "2890:2888"
      - "3890:3888"
    volumes:
      - "./zoo3/zoo.cfg:/opt/zookeeper-3.4.13/conf/zoo.cfg"
      - "./zoo3/data:/opt/zookeeper-3.4.13/data"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      zoo_kafka:
        ipv4_address: 172.23.0.13

networks:
  zoo_kafka:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/24
          gateway: 172.23.0.1
